### ISSUE TITLE
Using harmony test net but account description on top right says "unsupported network"

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#93] opened 2022-03-04 07:00 UTC
**Describe the bug**
Using harmony test net but account description on top right says "unsupported network"

**Screenshot**
<img width="591" alt="Screenshot 2022-03-04 at 12 29 34 PM" src="https://user-images.githubusercontent.com/88843644/156715173-0541dfaa-bcdc-4ebf-872c-a5343b668ba8.png">

**Comment by AlwaysHungrie** [comment] 2022-03-07 05:28
Duplicate of #91

**Closed by AlwaysHungrie** 2022-03-07 05:28 UTC
Labels: bug
