### ISSUE TITLE
No check of links for project links in apply for a grant form

### ISSUE THREAD

**Issue by rajkaria** [questbook/grants-frontend#107] opened 2022-03-04 07:25 UTC
<img width="475" alt="Screenshot 2022-03-04 at 12 54 07" src="https://user-images.githubusercontent.com/29420323/156718332-15c00094-1db3-4fd6-bce2-082031833756.png">

**Comment by rajkaria** [comment] 2022-03-04 07:25
I was able to add normal text in "project link 1"

**Comment by AlwaysHungrie** [comment] 2022-03-07 06:10
Duplicate of #96

**Closed by AlwaysHungrie** 2022-03-07 06:10 UTC
Labels: bug
