### ISSUE TITLE
Switching network in metamask makes the user logout

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#101] opened 2022-03-04 07:16 UTC
**Describe the bug**
Switch between any 2 networks while you have logged in with metamask and you will logout in the grants frontend. Remix and other apps dont logout; they smoothly switch the network and update the network name in frontend.
=

**Comment by AlwaysHungrie** [comment] 2022-03-07 05:47
Duplicate of #66

**Closed by AlwaysHungrie** 2022-03-07 05:47 UTC
Labels: bug
