### ISSUE TITLE
At times, submit application CTA does not work 

### ISSUE THREAD

**Issue by roohchillsharma** [questbook/grants-frontend#128] opened 2022-03-04 12:42 UTC
https://www.loom.com/share/c33cec00d4454c1983ddc1c020412a27

**Comment by abhilashi** [comment] 2022-03-06 13:46
@AlwaysHungrie @SahilVasava is this a rinkeby issue?

**Comment by SahilVasava** [comment] 2022-03-07 06:19
@abhilashi It's because of incorrect email in the form. But agree, this needs better handling of incorrect data format or missing issue.

**Comment by AlwaysHungrie** [comment] 2022-03-07 07:07
Duplicate of #98

**Closed by AlwaysHungrie** 2022-03-07 07:07 UTC
Labels: bug
